### ISSUE TITLE
 [Crowdin] "Proxy" string

### ISSUE THREAD

**Issue by kaktusus** [FreeCAD/FreeCAD-translations#153] opened 2022-05-20 19:23 UTC
https://crowdin.com/translate/freecad/32150/en-pl#6596924

`Proxy`

The string is marked as **hidden** and **duplicate** but is still used, I just modified the translation and it was applied in the GUI.

![image](https://user-images.githubusercontent.com/39754351/169597675-1571fa5d-493b-4c95-a2d8-713999b56002.png)

**Comment by kaktusus** [comment] 2022-06-04 08:05
There are more similar cases. Should I report them all here?
For example
1.  https://forum.freecadweb.org/viewtopic.php?style=4&f=21&t=69109&sid=f0367f8707791042e8d2b914a5be630a
2.  https://forum.freecadweb.org/viewtopic.php?style=4&f=21&t=69136

I guess this isn't the end ...

**Comment by chennes** [comment] 2023-04-23 00:24
For the "proxy" string: it was hidden as a duplicate of a Glossary entry added by @kaktusus -- I've removed the "hidden" attribute, but I'm not sure what to do about the glossary entry. It does not seem necessary.

**Comment by kaktusus** [comment] 2023-04-23 04:37
From the point of view of GUI translations, the glossary may be negligible.

**Closed** 2023-04-23 04:38 UTC
