### ISSUE TITLE
Tool for translators to check accuracy of translations with a script

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-translations#14] opened 2021-06-11 18:29 UTC
A tool was created by a user on the FC forum that can run within FC as a macro and take screenshots of different preferences and dialogues. It then saves those screenshots for later review of the accuracy of the translations. 

Figure out how to make this macro cross-platform and used by serious translators

More info pending

Edit: forum thread: https://forum.freecadweb.org/viewtopic.php?style=10&f=22&t=55460&start=20#p480412

**Comment by kaktusus** [comment] 2021-06-11 18:40
The most effective method is to check every signature and every label, its disadvantage is that it is very labor intensive.

**Comment by luzpaz** [comment] 2021-06-11 20:06
>  My only concern is the amount of work that will be generated for developers to fix bugs.

It's OK, we need to track whatever is broken.

**Comment by kaktusus** [comment] 2021-06-11 20:18
I took a look at the Arch module, just in case Yorik was bored.
I know it's his favorite.
:-P

**Comment by kaktusus** [comment] 2021-06-12 06:00
> Edit: I found the link to the forum thread

Thanks.

I have familiarized myself with this topic.
However, I will not confirm that I will use this macro in the future.

The linux distribution I'm using has a built in tool for taking screenshots. It is equipped with advanced options that offer a lot of possibilities.
Without it I would not be able to make many screenshots for this corner of FreeCAD on GitHub.

**Comment by kaktusus** [comment] 2021-06-12 06:55
![obraz](https://user-images.githubusercontent.com/39754351/121767917-a70c5d80-cb5b-11eb-9b11-51e93855a749.png)

I was curious about the command message for string conversion

I highlighted "untranslated" in red

the translation rate is 100% ...

**Comment by kaktusus** [comment] 2021-06-13 05:50
Something stopped working ...
I apply changes _(Crowdin)_ within the **draft.ts** file, download it ...
I do the conversion with the prepared command, 
after launching FreeCAD, the changes are not visible ...
WTF?

**Comment by kaktusus** [comment] 2021-06-13 05:55
uuuupppss

I found the cause ...
The file is downloaded with a name starting with a lowercase letter ...
FreeCAD requires a file with a name starting with a capital letter.

**Comment by luzpaz** [comment] 2021-06-13 20:28
Should we change 'draft` to `Draft` then?

**Comment by kaktusus** [comment] 2021-06-14 03:03
Exactly, that's my suggestion

**Comment by luzpaz** [comment] 2021-06-15 01:34
I'm worried that will make all the `draft.ts` translations invalid

**Comment by kaktusus** [comment] 2021-06-15 03:16
Don't worry about it.
When I download a file to test I save it with a name change and everything works fine.
https://vimeo.com/563056813

**Comment by kaktusus** [comment] 2021-11-06 14:25
Allow me to stray from the mainstream on this topic and make a seed of a separate conversation.

A few days ago, after reaching 100% in interface translation, I decided to evaluate the quality of GUI translations in the FEM module.

This is also due to a new member of the Polish translators group who works with the FEM environment on a daily basis.

I must say that we have a lot of work ahead of us to improve the quality of GUI translations in this workspace.
I expect to report dozens of problems, and the number will not be less than ~ 50 ...

Sincerest greetings to all involved.

**Comment by kaktusus** [comment] 2021-12-05 10:44
Since 



```
OS: Debian GNU/Linux bookworm/sid (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.26375 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 8a6e3d1)
Hash: 8a6e3d1b766a34546806b22d750929c2d00e30a6
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: Polish/Poland (pl_PL)
```


The mechanism for manually updating FC with translations from Crowdin was broken!

**it's not good**

**Comment by luzpaz** [comment] 2021-12-30 12:33
what's the mechanism workflow again?

**Comment by kaktusus** [comment] 2021-12-30 13:41
Yes,
I use it all the time

**Comment by kaktusus** [comment] 2021-12-30 14:21
I wonder about one issue that we have touched upon with the team of Polish FC translators.

_Applies to the translation of external workbenches in the program. _
Is this issue difficult to implement? 
Some guidance on this issue for programmers would be useful.

**Comment by luzpaz** [comment] 2023-04-16 20:07
CC @chennes (you mentioned something about unclear workflow for how translators can test translations, here's a ticket related to that)

**Comment by kaktusus** [comment] 2023-04-17 04:29
We have had the issues of self-testing of translations by translators resolved for a long time ...
https://github.com/FreeCAD/FreeCAD-translations/#testing

**Comment by kaktusus** [comment] 2023-09-17 19:16
@luzpaz 
Is this ticket suitable for closing?

**Closed** 2023-09-17 21:38 UTC
